#-------------------------------
# General Site Settings

title: A:|:Z
description: designer // developer // artist
email: info@admirzukic.tk

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

blurb: >
  ...who has some other skills too


#-------------------------------
# Skills Section

skills:
  - {name: Communication, value: '8'}
  - {name: Organization, value: '7'}
  - {name: Learning, value: '8'}
  - {name: Teaching, value: '7'}
  - {name: Planning, value: '7'}
  - {name: Visual Design, value: '6'}
  - {name: Web Development, value: '8'}
  - {name: Programming, value: '7'}


#-------------------------------
# Work Section

projects:
- {name: AtZiMedia Logo Concept, folder: 'proj-1'}
- {name: Leptirela Logo Concept, folder: 'proj-2'}
- {name: Kajak Kanu Klub Ključ Website Maintenance, folder: 'proj-3'}
- {name: GetSetPet UK Website Maintenance, folder: 'proj-4'}
- {name: Cart by Call Website Development, folder: 'proj-5'}
- {name: Infoline Team Website Development, folder: 'proj-6'}
- {name: Lenient Website Development, folder: 'proj-7'}
- {name: Rieber Services Website Mockup, folder: 'proj-8'}

#-------------------------------
# Arts Section

arts:
- {name: Happy Bush, folder: 'art-1'}
